apiVersion: v1
kind: Service
metadata:
  name: guptak-micro
  namespace: guptak
spec:
  selector:
    app: guptak-micro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

